/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vendasGUI;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author focuswts
 */
public class searchProductGUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form searchProductGUI
     */
    private Connection con = lib.connection.connect();

    public searchProductGUI() {
        initComponents();
        txt_SearchField.setText(sellGUI.txt_codProduto.getText());
    }

    public void preenche_grid() {
        DefaultTableModel aModel = (DefaultTableModel) this.tb_SearchResults.getModel();
        try {

            int numlinhas = aModel.getRowCount();
            for (int i = 0; i < numlinhas; i++) {
                aModel.removeRow(0);
            }
            String filtro = txt_SearchField.getText();

            //Verifica Qual Método Será Utilizado A Partir Dos Botoes//
            String sql = "";
            String stType = "";
            if (rb_Codigo.isSelected() == true) {
                sql = "SELECT produtos.idprod,produtos.desprod,produtos.quantidade,produtos.valunit from produtos where idprod = ?";
                stType = "codigo";
            }
            if (rb_Nome.isSelected() == true) {

                sql = "SELECT produtos.idprod,produtos.desprod,produtos.quantidade,produtos.valunit from produtos where desprod LIKE ?";
                stType = "descricao";
            }
///////////////////////////////////Fim Verificação Botoes//////////////////////
            PreparedStatement st = (PreparedStatement) con.prepareStatement(sql);
            ////////////////Definiçao Dos Statements/////////////
            if (stType.equals("codigo")) {
                int codigo = Integer.parseInt(txt_SearchField.getText());
                st.setInt(1, codigo);
            }
            if (stType.equals("descricao")) {
                String nome = txt_SearchField.getText();
                st.setString(1, "%" + nome + "%");
            }
//////////////////////////////////////////////////////////////////
            ResultSet rs = st.executeQuery();
            ResultSetMetaData rsmt = rs.getMetaData();
            int numcol = rsmt.getColumnCount();
            while (rs.next()) {
                Object[] objects = new Object[numcol];
                for (int i = 0; i < numcol; i++) {
                    objects[i] = rs.getObject(i + 1);
                }
                aModel.addRow(objects);

            }
        } catch (SQLException e) {
        }

    }

    public void GetCartItemData() {
        String xCodigo = this.tb_SearchResults.getValueAt(tb_SearchResults.getSelectedRow(), 0).toString();
        String xDescricao = this.tb_SearchResults.getValueAt(tb_SearchResults.getSelectedRow(), 1).toString();
        String xQuantidade = "1";
        String xValUnitario = this.tb_SearchResults.getValueAt(tb_SearchResults.getSelectedRow(), 3).toString();

        //Define Valores Para A Classe De Modelo//////
        sellItemsClass modelVendas = new sellItemsClass();
        modelVendas.setCodProduto(xCodigo);
        modelVendas.setDesc_Produto(xDescricao);
        modelVendas.setQtd_Produto(xQuantidade);
        modelVendas.setVal_Unitario(xValUnitario);
        modelVendas.setEnabled(true);
        ////////////////////////////////////////
        ///Executa Método Static Para Atribuição De Valores/////////
        sellGUI.exportarComponentes(modelVendas);
        ////////////////////////////////////////////////////////////
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rb_Codigo = new javax.swing.JRadioButton();
        rb_Nome = new javax.swing.JRadioButton();
        txt_SearchField = new javax.swing.JTextField();
        btn_Buscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_SearchResults = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_Quantidade = new javax.swing.JTextField();
        Ftxt_ValorUnitario = new javax.swing.JFormattedTextField();
        btn_Confirma = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Pesquisar Produto Por:");

        buttonGroup1.add(rb_Codigo);
        rb_Codigo.setSelected(true);
        rb_Codigo.setText("Código");

        buttonGroup1.add(rb_Nome);
        rb_Nome.setText("Nome");

        btn_Buscar.setIcon(new javax.swing.ImageIcon("/home/focuswts/Icons For Development/Aesthetica Icons Set/png/24x24/search.png")); // NOI18N
        btn_Buscar.setText("Buscar");
        btn_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarActionPerformed(evt);
            }
        });

        tb_SearchResults.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Quantidade", "Preço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_SearchResults.getTableHeader().setReorderingAllowed(false);
        tb_SearchResults.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_SearchResultsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_SearchResults);

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("Quantidade:");

        jLabel3.setText("Valor Unitário");

        txt_Quantidade.setEditable(false);

        Ftxt_ValorUnitario.setEditable(false);

        btn_Confirma.setIcon(new javax.swing.ImageIcon("/home/focuswts/Icons For Development/Aesthetica Icons Set/png/16x16/accept.png")); // NOI18N
        btn_Confirma.setText("Confirmar");
        btn_Confirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ConfirmaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Quantidade, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ftxt_ValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(btn_Confirma)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txt_Quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ftxt_ValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(btn_Confirma)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_SearchField)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(rb_Codigo)
                                .addGap(18, 18, 18)
                                .addComponent(rb_Nome)))
                        .addGap(18, 18, 18)
                        .addComponent(btn_Buscar)
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(rb_Codigo)
                    .addComponent(rb_Nome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarActionPerformed

        preenche_grid();
    }//GEN-LAST:event_btn_BuscarActionPerformed

    private void btn_ConfirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ConfirmaActionPerformed
        GetCartItemData();
    }//GEN-LAST:event_btn_ConfirmaActionPerformed

    private void tb_SearchResultsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_SearchResultsMouseClicked
        txt_Quantidade.setText(tb_SearchResults.getValueAt(tb_SearchResults.getSelectedRow(), 2).toString());
        Ftxt_ValorUnitario.setText(tb_SearchResults.getValueAt(tb_SearchResults.getSelectedRow(), 3).toString());
    }//GEN-LAST:event_tb_SearchResultsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField Ftxt_ValorUnitario;
    private javax.swing.JButton btn_Buscar;
    private javax.swing.JButton btn_Confirma;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rb_Codigo;
    private javax.swing.JRadioButton rb_Nome;
    private javax.swing.JTable tb_SearchResults;
    private javax.swing.JTextField txt_Quantidade;
    private javax.swing.JTextField txt_SearchField;
    // End of variables declaration//GEN-END:variables
}
