/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Administrator.gui;

import com.mysql.jdbc.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Faccar
 */
public class ProductsManagement extends javax.swing.JInternalFrame {

    /**
     * Creates new form ProductsManagement
     */
    private Connection con = lib.connection.connect();
    private String operacao;

    public ProductsManagement() {
        initComponents();
        preenche_tlistacateg();
        preenche_grid();
        Block();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_Id = new javax.swing.JTextField();
        txt_Descricao = new javax.swing.JTextField();
        txt_Quantidade = new javax.swing.JTextField();
        txt_Valunit = new javax.swing.JTextField();
        txt_filtro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cb_Categoria = new javax.swing.JComboBox<>();
        btn_Filtrar = new javax.swing.JButton();
        dt_Dtultmov = new com.toedter.calendar.JDateChooser();
        btn_Limpar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_Produtos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btn_Novo = new javax.swing.JButton();
        btn_Excluir = new javax.swing.JButton();
        btn_Alterar = new javax.swing.JButton();
        btn_Gravar = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gerenciamento De Produtos");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setText("Id Produto");

        jLabel4.setText("Descricao");

        jLabel5.setText("Quantidade");

        jLabel6.setText("Valor Unitario");

        jLabel7.setText("Categoria");

        jLabel8.setText("Filtro");

        jLabel9.setText("Data Ult Mov");

        cb_Categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btn_Filtrar.setText("Filtrar");
        btn_Filtrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FiltrarActionPerformed(evt);
            }
        });

        dt_Dtultmov.setDateFormatString("yyyy-MM-dd");

        btn_Limpar.setText("Limpar");
        btn_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dt_Dtultmov, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_Descricao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_Quantidade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_Valunit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(cb_Categoria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                                .addComponent(btn_Limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(3, 3, 3)
                        .addComponent(txt_filtro, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Filtrar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel3))
                    .addComponent(txt_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel4))
                    .addComponent(txt_Descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel5))
                    .addComponent(txt_Quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel6))
                    .addComponent(txt_Valunit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(dt_Dtultmov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_Limpar)
                        .addGap(26, 26, 26)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(btn_Filtrar)
                    .addComponent(txt_filtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tb_Produtos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Descricao", "QTD", "Val.Unit", "Data.Ult.Mov", "Categoria"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_Produtos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_ProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_Produtos);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_Novo.setText("Novo");
        btn_Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NovoActionPerformed(evt);
            }
        });

        btn_Excluir.setText("Excluir");
        btn_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExcluirActionPerformed(evt);
            }
        });

        btn_Alterar.setText("Alterar");
        btn_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AlterarActionPerformed(evt);
            }
        });

        btn_Gravar.setText("Gravar");
        btn_Gravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GravarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_Novo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_Gravar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Alterar, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_Alterar, btn_Excluir, btn_Gravar, btn_Novo});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Novo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Excluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Alterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Gravar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addContainerGap())
        );

        setBounds(0, 0, 725, 485);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NovoActionPerformed
        this.operacao = "gravar";
        System.out.println(operacao);
        unBlock();
    }//GEN-LAST:event_btn_NovoActionPerformed

    private void btn_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AlterarActionPerformed
        this.operacao = "alterar";
        System.out.println(operacao);
       unBlock();
    }//GEN-LAST:event_btn_AlterarActionPerformed

    private void btn_GravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GravarActionPerformed
        
        if("alterar".equals(operacao)){
        Atualizar();
        }else{
        Gravar();
        }
        preenche_grid();
    }//GEN-LAST:event_btn_GravarActionPerformed

    private void btn_LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LimparActionPerformed
        Limpar();
    }//GEN-LAST:event_btn_LimparActionPerformed

    private void tb_ProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_ProdutosMouseClicked

        try {
            DefaultTableModel aModel = (DefaultTableModel) this.tb_Produtos.getModel();
            txt_Id.setText(tb_Produtos.getValueAt(tb_Produtos.getSelectedRow(), 0).toString());
            txt_Descricao.setText(tb_Produtos.getValueAt(tb_Produtos.getSelectedRow(), 1).toString());
            txt_Quantidade.setText(tb_Produtos.getValueAt(tb_Produtos.getSelectedRow(), 2).toString());
            txt_Valunit.setText(tb_Produtos.getValueAt(tb_Produtos.getSelectedRow(), 3).toString());
            String date = aModel.getValueAt(tb_Produtos.getSelectedRow(), 4).toString();
            dt_Dtultmov.setDate(dma_to_amd(date));
            String categ = tb_Produtos.getValueAt(tb_Produtos.getSelectedRow(), 5).toString();
            cb_Categoria.setSelectedItem(categ);
        } catch (Exception e) {

        }
    }//GEN-LAST:event_tb_ProdutosMouseClicked

    private void btn_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExcluirActionPerformed
        deletar();
        preenche_grid();
    }//GEN-LAST:event_btn_ExcluirActionPerformed

    private void btn_FiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FiltrarActionPerformed
        procurar();
    }//GEN-LAST:event_btn_FiltrarActionPerformed

    public void preenche_grid() {
        DefaultTableModel aModel = (DefaultTableModel) this.tb_Produtos.getModel();
        try {

            int numlinhas = aModel.getRowCount();
            for (int i = 0; i < numlinhas; i++) {
                aModel.removeRow(0);
            }
            String sql = "select produtos.idprod, produtos.desprod, produtos.quantidade,produtos.valunit, date_format(produtos.ultmov, '%d/%m/%Y'), categoria.descateg, categoria.idcateg from produtos, categoria where produtos.codcateg=categoria.idcateg order by produtos.desprod";
            PreparedStatement st = (PreparedStatement) con.prepareStatement(sql);
            ResultSet rs = st.executeQuery();
            ResultSetMetaData rsmt = rs.getMetaData();
            int numcol = rsmt.getColumnCount();
            while (rs.next()) {
                Object[] objects = new Object[numcol];
                for (int i = 0; i < numcol; i++) {
                    objects[i] = rs.getObject(i + 1);
                }
                aModel.addRow(objects);

            }
        } catch (SQLException e) {
        }

    }

    public void Gravar() {
        try {
            int idProd = Integer.parseInt(this.txt_Id.getText());
            String desProd = this.txt_Descricao.getText();
            double Qtd = Double.parseDouble(this.txt_Quantidade.getText());
            double valUnit = Double.parseDouble(this.txt_Valunit.getText());
            int codCateg = this.cb_Categoria.getSelectedIndex();
            java.util.Date utilDate = (java.util.Date) dt_Dtultmov.getDate();
            java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());

            String sql = "INSERT INTO produtos (idprod,desprod,quantidade,valunit,codcateg,ultmov) values (?,?,?,?,?,?)";
            PreparedStatement stt = con.prepareStatement(sql);
            stt.setInt(1, idProd);
            stt.setString(2, desProd);
            stt.setDouble(3, Qtd);
            stt.setDouble(4, valUnit);
            stt.setInt(5, codCateg);
            stt.setDate(6, sqlDate);
            stt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Salvo Com Sucesso!");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Ocorreu Algum Erro!");
        }

    }//final gravar//

    public void preenche_tlistacateg() {
        try {
            cb_Categoria.removeAllItems();
            PreparedStatement st = con.prepareStatement("select idcateg,descateg from categoria order by descateg");
            ResultSet rs = st.executeQuery();
            cb_Categoria.insertItemAt("-- Selecione --", 0);
            int x = 1;
            while (rs.next()) {
                cb_Categoria.insertItemAt(rs.getString("descateg"), x);
                x++;
            }
            cb_Categoria.setSelectedIndex(0);
        } catch (Exception sqlEx) {
        }
    }

    public void Block() {
        try {
            txt_Id.setEnabled(false);
            txt_Descricao.setEnabled(false);
            txt_Quantidade.setEnabled(false);
            txt_Valunit.setEnabled(false);
            cb_Categoria.setEnabled(false);
            dt_Dtultmov.setEnabled(false);
            System.out.println("Blocked!!");
        } catch (Exception e) {
        }
    }//fim BLOCK//

    public void unBlock() {
        try {
            txt_Id.setEnabled(true);
            txt_Descricao.setEnabled(true);
            txt_Quantidade.setEnabled(true);
            txt_Valunit.setEnabled(true);
            cb_Categoria.setEnabled(true);
            dt_Dtultmov.setEnabled(true);
        } catch (Exception e) {
            System.out.println("Unblocked!!");
        }
    }

    public void Limpar() {
        txt_Descricao.setText("");
        txt_Quantidade.setText("");
        txt_Valunit.setText("");
        cb_Categoria.setSelectedIndex(0);
        dt_Dtultmov.setDate(null);
    }

    public void Atualizar() {
        try {

            int id = Integer.parseInt(this.txt_Id.getText());
            String desc = this.txt_Descricao.getText();
            String qtd = this.txt_Quantidade.getText();
            String valUnit = this.txt_Valunit.getText();
            int codCateg = this.cb_Categoria.getSelectedIndex();
            java.util.Date ultMov = this.dt_Dtultmov.getDate();
            String sql = "UPDATE produtos SET desprod = ?,quantidade = ?,valunit = ?,codcateg = ?,ultmov = ? where idprod = ?";
            PreparedStatement st = con.prepareStatement(sql);
            st.setString(1, desc);
            st.setString(2, qtd);
            st.setString(3, valUnit);
            st.setInt(4, codCateg);
            st.setDate(5, new java.sql.Date(dt_Dtultmov.getDate().getTime()));
            st.setInt(6, id);
            st.executeUpdate();
            JOptionPane.showMessageDialog(this, "Atualização Com Sucesso!");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Ocorreu Algum Erro!");
        }

    }

    public void deletar() {
        try {
            int id = Integer.parseInt(this.txt_Id.getText());
            String sql = "DELETE FROM produtos WHERE idprod = ?";
            PreparedStatement st = con.prepareStatement(sql);
            st.setInt(1, id);
            st.executeUpdate();
            JOptionPane.showMessageDialog(this, "Registro Deletado Com Sucesso!");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Ocorreu Algum Erro!");
        }

    }

    public void procurar() {
        DefaultTableModel aModel = (DefaultTableModel) this.tb_Produtos.getModel();
        try {
            String filtro = txt_filtro.getText();
            int numlinhas = aModel.getRowCount();
            for (int i = 0; i < numlinhas; i++) {
                aModel.removeRow(0);
            }
            String sql = "SELECT * FROM produtos where desprod LIKE ?";
            PreparedStatement st = con.prepareStatement(sql);
            st.setString(1, "%" + filtro + "%");
            ResultSet rs = st.executeQuery();
            ResultSetMetaData rsmt = rs.getMetaData();
            int numcol = rsmt.getColumnCount();
            while (rs.next()) {
                Object[] objects = new Object[numcol];
                for (int i = 0; i < numcol; i++) {
                    objects[i] = rs.getObject(i + 1);
                }
                aModel.addRow(objects);

            }
        } catch (SQLException e) {
        }

    }

    public String amd_to_dma(java.sql.Date d) {
        String resp = "";
        if (d != null) {
            String sdat = d.toString();
            String sano = sdat.substring(0, 4);
            String smes = sdat.substring(5, 7);
            String sdia = sdat.substring(8, 10);
            resp = sdia + "/" + smes + "/" + sano;
        }
        return resp;
    }

    public java.sql.Date dma_to_amd(String d) {
        java.sql.Date dataresp = null;
        int tam = d.length();
        if (d != null && tam == 10) {
            String sdia = d.substring(0, 2);
            String smes = d.substring(3, 5);
            String sano = d.substring(6, 10);
            dataresp = java.sql.Date.valueOf(sano + "-" + smes + "-" + sdia);
        }
        return dataresp;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Alterar;
    private javax.swing.JButton btn_Excluir;
    private javax.swing.JButton btn_Filtrar;
    private javax.swing.JButton btn_Gravar;
    private javax.swing.JButton btn_Limpar;
    private javax.swing.JButton btn_Novo;
    private javax.swing.JComboBox<String> cb_Categoria;
    private com.toedter.calendar.JDateChooser dt_Dtultmov;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_Produtos;
    private javax.swing.JTextField txt_Descricao;
    private javax.swing.JTextField txt_Id;
    private javax.swing.JTextField txt_Quantidade;
    private javax.swing.JTextField txt_Valunit;
    private javax.swing.JTextField txt_filtro;
    // End of variables declaration//GEN-END:variables
}
